"""Colour transfer baked into a 3D LUT.

The reference's look is matched statistically in LAB - per-channel mean and
spread - and written as a .cube that ffmpeg's lut3d applies in a single pass.

This is deliberately an *appearance* match rather than an attempt to recover
the transform the reference editor actually used. Recovering that would need
their ungraded source, which we never have; matching the appearance needs only
the graded result, which we do.
"""
from __future__ import annotations

import pathlib
from dataclasses import dataclass

import cv2
import numpy as np

DEFAULT_SIZE = 33


@dataclass(frozen=True)
class ColorStats:
    """Per-channel mean and standard deviation in OpenCV's LAB space."""

    mean: tuple[float, float, float]
    std: tuple[float, float, float]


def _grid(size: int) -> np.ndarray:
    """LUT sample points in .cube order: red varies fastest, then green, blue."""
    axis = np.linspace(0.0, 1.0, size, dtype=np.float32)
    red, green, blue = np.meshgrid(axis, axis, axis, indexing="ij")
    return np.stack([red.T.ravel(), green.T.ravel(), blue.T.ravel()], axis=1).reshape(-1, 1, 3)


def transfer(rgb: np.ndarray, source: ColorStats, target: ColorStats, strength: float) -> np.ndarray:
    """Reinhard-style statistical transfer, applied in LAB and returned as RGB."""
    lab = cv2.cvtColor(rgb.astype(np.float32), cv2.COLOR_RGB2LAB)

    source_std = np.array(source.std, dtype=np.float32)
    target_std = np.array(target.std, dtype=np.float32)
    # A near-flat source channel carries no information to rescale; leaving the
    # ratio at 1 avoids amplifying noise into a colour cast.
    ratio = np.where(source_std < 1e-3, 1.0, target_std / np.maximum(source_std, 1e-3))

    shifted = (lab - np.array(source.mean, dtype=np.float32)) * ratio + np.array(
        target.mean, dtype=np.float32
    )
    blended = lab + (shifted - lab) * float(strength)
    blended[:, :, 0] = np.clip(blended[:, :, 0], 0.0, 100.0)
    blended[:, :, 1:] = np.clip(blended[:, :, 1:], -127.0, 127.0)

    return np.clip(cv2.cvtColor(blended, cv2.COLOR_LAB2RGB), 0.0, 1.0)


def write_lut(
    source: ColorStats,
    target: ColorStats,
    out_path: str | pathlib.Path,
    size: int = DEFAULT_SIZE,
    strength: float = 1.0,
) -> pathlib.Path:
    out_path = pathlib.Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    mapped = transfer(_grid(size), source, target, strength).reshape(-1, 3)

    lines = [
        "# generated by halfheaven - statistical LAB colour transfer",
        f"LUT_3D_SIZE {size}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",
    ]
    lines += [f"{r:.6f} {g:.6f} {b:.6f}" for r, g, b in mapped]
    out_path.write_text("\n".join(lines) + "\n")
    return out_path
